### ISSUE TITLE
Can't upgrade to @nuxt/scripts ^0.9.0 because peerDependencies from @nuxtjs/turnstile is: "@nuxt/scripts": "^0.6.0 || ^0.7.0 || ^0.8.0"

### ISSUE THREAD

**Issue by bernhardberger** [nuxt-modules/turnstile#333]
### 🐛 The bug

basically the successor of: https://github.com/nuxt-modules/turnstile/issues/327 

```
 npx nuxi@latest module add turnstile
ℹ Installing @nuxtjs/turnstile@latest development dependency                                      2:43:36 PM
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: outletcars-frontend-app@undefined
npm error Found: @nuxt/scripts@0.9.2
npm error node_modules/@nuxt/scripts
npm error   dev @nuxt/scripts@"^0.9.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @nuxt/scripts@"^0.6.0 || ^0.7.0 || ^0.8.0" from @nuxtjs/turnstile@0.9.4
npm error node_modules/@nuxtjs/turnstile
npm error   dev @nuxtjs/turnstile@"0.9.4" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/beb/.npm/_logs/2024-09-16T12_43_36_147Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/beb/.npm/_logs/2024-09-16T12_43_36_147Z-debug-0.log

 ERROR  Command failed with exit code 1: npm install -D @nuxtjs/turnstile@latest                   2:43:37 PM  

  at makeError (node_modules/nuxi/dist/chunks/index7.mjs:578:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index7.mjs:1504:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async executeCommand (node_modules/nuxi/dist/shared/nuxi.e6ef3ea5.mjs:43:3)
  at async addDependency (node_modules/nuxi/dist/shared/nuxi.e6ef3ea5.mjs:208:3)
  at async Object.setup (node_modules/nuxi/dist/chunks/add2.mjs:145:19)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1620:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1639:11)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1777:7)


✔ Install failed for @nuxtjs/turnstile@latest. 
```

@danielroe Do we really need that strict peerDep restrictions now that Nuxt Scripts is released? This turns into dep hell really quickly. I'm asking you because you made the last PR to restrict it to 0.6-0.8 here https://github.com/nuxt-modules/turnstile/pull/328

### 🛠️ To reproduce

https://stackblitz.com/github/nuxt-modules/turnstile/tree/main/playground

### 🌈 Expected behaviour

I expect not being stuck on an outdated version of a peerDep if there's no need

**Comment by dargmuesli** [comment]
I've published a path extending the supported version range once more, but I keep this issue open for Daniel to answer your question.

**Comment by danielroe** [comment]
Yes, it is still needed. It’s possible there will be breaking changes until it released stably as v1.

We’ll do our best to release quickly when it bumps version.
